---
# Example single-node OpenStack deployment.

- name: Configure instance
  hosts: all
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
  roles:
    - role: nginx
      nginx_sites:
      - certs
      - lms
      - cms
      - xqueue
      nginx_default_sites:
      - lms
    - edxlocal
    - memcache
    - mongo_3_6
    - role: rabbitmq
      rabbitmq_ip: '127.0.0.1'
    - role: edxapp
      celery_worker: True
    - edxapp
    - role: xqueue
      update_users: True
    - elasticsearch
    - role: postfix
      when: POSTFIX_QUEUE_EXTERNAL_SMTP_HOST is not defined or POSTFIX_QUEUE_EXTERNAL_SMTP_HOST == ''
    - role: postfix_queue
      when: POSTFIX_QUEUE_EXTERNAL_SMTP_HOST != ''
    - guacd
    - hastexo_xblock
