---
# Example multi-node OpenStack deployment.

- name: Configure deployment node
  hosts: localhost
  become: True
  gather_facts: True
  roles:
    - role: postfix_queue
      when: POSTFIX_QUEUE_EXTERNAL_SMTP_HOST != ''

- name: Configure backend servers
  hosts: backend_servers
  become: True
  gather_facts: True
  roles:
    - common
    - mongo_3_6
    - elasticsearch
    - { role: 'mariadb', MARIADB_CREATE_DBS: 'yes' }
    - role: postfix_queue
      when: POSTFIX_QUEUE_EXTERNAL_SMTP_HOST != ''
    - memcache

# RabbitMQ needs to be built serially
- name: Configure Redis
  hosts: backend_servers
  become: True
  gather_facts: True
  serial: 1
  roles:
    - redis

- name: Configure app servers
  hosts: app_servers:tmp_app_servers:app_master
  become: True
  gather_facts: True
  roles:
    - supervisor
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - xqueue
      nginx_default_sites:
      - lms
    - role: edxapp
      celery_worker: True
    - edxapp
    - role: xqueue
      update_users: True
    - certs
    - role: user_retirement_pipeline
      when: COMMON_RETIREMENT_SERVICE_SETUP
    - role: postfix_queue
      when: POSTFIX_QUEUE_EXTERNAL_SMTP_HOST != ''
    - guacd
    - hastexo_xblock

- name: Stop all services on app master
  hosts: app_master
  become: True
  gather_facts: True
  roles:
    - stop_all_edx_services
